### ISSUE TITLE
Could you attach a configuration file

### ISSUE THREAD

**Issue by ChenBarryHu** [ZhaoyangLyu/Point_Diffusion_Refinement#5]
Dear ZhaoYang,

There is no such file `exp_configs/mvp_configs/config_standard_attention_real_3072_partial_points_rot_90_scale_1.2_translation_0.1.json` in the repo. 

Is it possible for you to attach a configuration file?

Thanks!

**Comment by ZhaoyangLyu** [comment]
It's in the folder pointnet2: pointnet2/exp_configs/mvp_configs/config_standard_attention_real_3072_partial_points_rot_90_scale_1.2_translation_0.1.json

**Comment by ChenBarryHu** [comment]
Thank you!
